version: '3.1'
services:
  db:
    image: vuhtang/web_lab_db_mysql
    container_name: my-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    restart: always
  app:
    image: vuhtang/web_lab
    container_name: application
    ports:
      - "8080:8080"
    environment:
      DB_USER: admin
      DB_PASSWORD: admin
    restart: always
    links:
      - db
